<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wishlist"
 *
 * Auto generated by Extension Builder 2015-07-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Wishlist',
	'description' => 'Extension to list wishes in a list. Wishes can be fulfilled and user gets an email with contact and bank data. ',
	'category' => 'plugin',
	'author' => 'Michel Georgy',
	'author_email' => 'mgeorgy@tamtec.ch',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.1.0-7.3.99',
            'x4ebase' => '6.2-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);